# Project information
site_name: Web3 Pi
site_url: https://docs.web3pi.io/

# Repository
repo_name: Source-Code
repo_url: https://github.com/Web3-Pi/Ethereum-On-Raspberry-Pi

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - stylesheets/extra.js

theme:
  name: material
  custom_dir: overrides
  logo: assets/color.svg
  favicon: assets/favicon.ico
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    #    - navigation.path
    #    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - navigation.footer
  icon:
    repo: fontawesome/brands/github
  language: en
  palette:
    primary: black
    scheme: slate

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Web3-Pi/Ethereum-On-Raspberry-Pi
      type: github
      repo: Web3-Pi/Ethereum-On-Raspberry-Pi
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/_Web3Pi_
    - icon: fontawesome/brands/discord
      link: https://discord.gg/aDMw5zeUZ4

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true


copyright: |
  &copy; 2025 <a href="https://github.com/Web3-Pi/Ethereum-On-Raspberry-Pi"  target="_blank" rel="noopener">Web3 Pi</a>

nav:
  - Home: 'index.md'
  - Introduction:
    - About Web3 Pi: 'introduction/web3-pi-project.md'
    - What is an Ethereum Node?: 'introduction/ethereum-node.md'
    - Can I earn with Web3 Pi?: 'introduction/staking.md'
    - Next Steps: 'introduction/next-steps.md'
  - Setup:
    - Prerequisites: 'setup/prerequisites.md'
    - Supported Configurations: 'setup/supported-configurations.md'
    - Single Mode Setup:
      - Required Hardware: 'setup/single-mode/hardware-checklist.md'
      - Recommended Hardware: 'setup/single-mode/hardware-recommendations.md'
      - Software Setup: 'setup/single-mode/software-setup.md'
      - Hardware Assembly: 'setup/single-mode/hardware-assembly.md'
      - Installation Monitoring: 'setup/single-mode/installation-monitoring.md'
    - Dual Mode Setup:
      - Required Hardware: 'setup/dual-mode/hardware-checklist.md'
      - Recommended Hardware: 'setup/dual-mode/hardware-recommendations.md'
      - Software Setup: 'setup/dual-mode/software-setup.md'
      - Hardware Assembly: 'setup/dual-mode/hardware-assembly.md'
      - Installation Monitoring: 'setup/dual-mode/installation-monitoring.md'
    - Maintenance Considerations: 'setup/considerations.md'
    - Next Steps: 'setup/next-steps.md'
  - Monitoring:
    - Installation Monitor: 'monitoring/installation-monitor.md'
    - Grafana: 'monitoring/grafana.md'
    - LCD: 'monitoring/lcd.md'
    - Monitoring via HTTP API: 'monitoring/system-monitor.md'
  - Management:
    - SSH: 'management/ssh.md'
    - Cockpit:
      - Dashboard: 'management/cockpit/dashboard.md' 
      - Web3 Pi Updater: 'management/cockpit/web3-pi-updater.md'
      - Web3 Pi Link: 'management/cockpit/web3-pi-link.md'
      - Web3 Pi Script Runner: 'management/cockpit/web3-pi-script-runner.md'
  - Welcome Box: 'welcome-box/index.md'
  - Use Cases:
    - Install in your wallet: 'use-cases/wallet.md'
    - Transaction Firewall: 'use-cases/transaction-firewall.md'
    - Solo Staking (coming soon): 'use-cases/solo-staking.md'
  - Support: 
    - Troubleshooting: 'support/troubleshooting.md'
    - Contact: 'support/contact.md'
  - Downloads: 'downloads/index.md'