# Project information
site_name: Web3 Pi
site_url: https://docs.web3pi.io/

# Repository
repo_name: Source-Code
repo_url: https://github.com/Web3-Pi/Ethereum-On-Raspberry-Pi

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - stylesheets/extra.js

theme:
  name: material
  custom_dir: overrides
  logo: assets/color.svg
  favicon: assets/favicon.ico
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    #    - navigation.path
    #    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - navigation.footer
  icon:
    repo: fontawesome/brands/github
  language: en
  palette:
    - scheme: slate

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Web3-Pi/Ethereum-On-Raspberry-Pi
      type: github
      repo: Web3-Pi/Ethereum-On-Raspberry-Pi
    # - icon: fontawesome/brands/twitter
    #   link: https://twitter.com/Web3Pi
    - icon: fontawesome/brands/discord
      link: https://discord.com/channels/684703559954333727/1244941802709192755

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html


copyright: |
  &copy; 2025 <a href="https://github.com/Web3-Pi/Ethereum-On-Raspberry-Pi"  target="_blank" rel="noopener">Web3 Pi</a>

nav:
  - Home: 'index.md'
  - Before You Start: 'before.md'
  - Hardware Setup:
      - 'prerequisites.md'
      - Hardware Checklist: 'hardware-checklist.md'
      - Hardware Recommendations: 'hardware-recommendations.md'
      - LCD Screen: 'lcd-screen.md'
      - UPS: 'ups.md'
  - Welcome Box: 'welcome-box.md'
  - Setup Guide:
      - 'full-setup/menu.md'
      - Hardware Assembly: 'full-setup/hardware.md'
      - 'Flashing the Boot Card: Single Device Node': 'full-setup/software-single.md'
      - 'Initiating and Monitoring the Installation: Single Device Node': 'full-setup/monitoring-installation-single.md'
      - 'Flashing the Boot Cards: Dual Device Node': 'full-setup/software-dual.md'
      - 'Initiating and Monitoring the Installation: Dual Device Node': 'full-setup/monitoring-installation-dual.md'
  - Connecting to Ethereum: 'connect-ethereum.md'
  - Managing Your Node: 
      - 'managing/menu.md'
      - Tuning, Monitoring and Maintenance Guide: 'managing/tuning-monitoring-maintenance.md'
      - Configuration Guide: 'managing/configuration.md'
      - Troubleshooting Guide: 'managing/troubleshooting.md'
      - Upgrade Guide: 'managing/upgrade.md'
