# Project information
site_name: Web3 Pi
site_url: https://docs.web3pi.io/

# Repository
repo_name: Source-Code
repo_url: https://github.com/Web3-Pi/Ethereum-On-Raspberry-Pi

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - stylesheets/extra.js

theme:
  name: material
  logo: assets/color.svg
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    #    - navigation.path
    #    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  icon:
    repo: fontawesome/brands/github
  language: en
  palette:
    - scheme: slate

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Web3-Pi/Ethereum-On-Raspberry-Pi
      type: github
      repo: Web3-Pi/Ethereum-On-Raspberry-Pi
    # - icon: fontawesome/brands/twitter
    #   link: https://twitter.com/Web3Pi
    - icon: fontawesome/brands/discord
      link: https://discord.com/channels/684703559954333727/1244941802709192755

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg


copyright: |
  &copy; 2025 <a href="https://github.com/Web3-Pi/Ethereum-On-Raspberry-Pi"  target="_blank" rel="noopener">Web3 Pi</a>



nav:
  - Menu 1:
      - Web3 Pi: 'index.md'
  - Menu 2:
      - Introduction: 'menu2.md'
  - Menu 3:
      - Introduction: 'menu3.md'
  - Menu 4:
      - Introduction: 'menu4.md'